version: "3.7" # Compose version. 3.7 is for docker engine 18.06.0+. 

# Compose file. dev environment overrides go in docker-dompose.override.yml, prod overrides in docker-compose.prod.yml

#name: ff-prod

services:
    couchdb:
        image: apache/couchdb:3
        volumes: #same in dev and prod
            # this is a named volume for database storage
            - couchdata:/opt/couchdb/data
            # host volume/bind mounts to map couchdb's config and logging to local directories
            # couch docker image creates docker.ini in local.d folder
            - ~/ff/couchmounts/config:/opt/couchdb/etc/local.d
            # must enable logging in config
            - ~/ff/couchmounts/logs:/opt/couchdb/log
        networks: # exposes to outside and lets API talk to couch
            - frontend

    api:
        image: ff-server
        # Build context, this will be the base path for dockerfile. Can specify both context and file itself w/ context: and dockerfile:
        build: server/
        environment: # can also use a .env file
            COUCHDB_URL: 'couchdb:5984' #access with 'http://user:pass@couchdb:5984'
        depends_on:
            - couchdb #specifies that couchdb spins up first
        networks:
            - frontend
        secrets:
            - couch_admin
            - couch_password
            - couch_replicator_user
            - couch_replicator_password
            - mail_from_address
            - mail_api_key


volumes:
    couchdata:

networks:
    backend: # TODO: with traefik I currently only need frontend in prod. In dev, mailhog's here.
        driver: bridge
    frontend: 
        name: frontend

# Secrets outside of swarm aren't shared over remote context since compose secrets just use a bind mount, must be on remote machine
secrets: # available in containers in /run/secrets/<secret_name>. Long notation can set file perms.
    # use explicit name for consistency between dev/stage/prod
    couch_admin:
        name: couch_admin # if not named, I think secret file will be <project_name>_<secret_name>
        file: ./secrets/couch_admin.txt
    couch_password:
        name: couch_password
        file: ./secrets/couch_password.txt
    couch_replicator_user:
        name: couch_replicator_user
        file: ./secrets/couch_replicator_user.txt
    couch_replicator_password:
        name: couch_replicator_password
        file: ./secrets/couch_replicator_password.txt
    mail_from_address:
        name: mail_from_address
        file: ./secrets/mail_from_address_test.txt
    mail_api_key:
        name: mail_api_key
        file: ./secrets/mail_api_key_test.txt
    traefik-dashboard-user:
        name: traefik-dashboard-user
        file: ./secrets/traefik-dashboard-user.txt
    #mail_from_address_test:
        #file: ./secrets/mail_from_address_test.txt
    #mail_api_key_test:
        #file: ./secrets/mail_api_key_test.txt
