version: "3.7" # TODO: should be updating this
# Compose file for production. dev environment overrides go in docker-dompose.override.yml
# TODO: might be better to have this be dev file and use overrides for production and staging?

services:
    couchdb:
        image: apache/couchdb:3
        volumes:
            # this is a named volume for database storage
            - couchdata:/opt/couchdb/data
            # host volume/bind mounts to map couchdb's config and logging to local directories
            # couch docker image creates docker.ini in local.d folder
            - ~/ff/couchmounts/config:/opt/couchdb/etc/local.d
            # must enable logging in config
            - ~/ff/couchmounts/logs:/opt/couchdb/log
        #environment:
            #COUCHDB_USER: admin
            #COUCHDB_PASSWORD: password #specify this differently for committing
        ports:
            - 5984:5984
        networks: # helps API talk to couch
            - backend
        secrets:
            - couch_admin
            - couch_password
    #ionic:
        #build: app/
        # not sure if need volumes, but what ports in container to map?
    api:
        image: ff-server
        # To build for prod, use export MY_SERVICE_VERSION=1.2.3, then docker-compose -f docker-compose.yml build,
        # then push. Could launch in prod (or staging) by exporting right vars, then using
        # docker stack deploy my-stack --compose-file docker-compose.yml --with-registry-auth
        # ^^^ for swarm mode
        # image: private.registry.mine/my-stack/my-service:${MY_SERVICE_VERSION:-latest}
        build: server/
        environment: # can also use a .env file
            COUCHDB_URL: 'couchdb:5984' #access with 'http://user:pass@couchdb:5984'
        depends_on:
            - couchdb #specifies that couchdb spins up first
        links:
            - couchdb
        networks:
            - backend
        ports:
            - "3000:3000"
        volumes:
            - ./server:/usr/src/app
        secrets:
            - couch_admin
            - couch_password
            - mail_from_address
            - mail_api_key
    #shell access to server with something like docker-compose run --rm web-cli maybe
    #web-cli:
        #image: ff-server #part of same image as api
        #networks:
            #- backend
        #command: sh # command to run on start, can be useful for setting up secrets in other containers
    # TODO: should have another service to serve the frontent?
    # reverse proxy, letsencrypt. Dashboard at http://localhost:8080/dashboard#/
    # TODO: for prod, put dashboard behind IP whitelist, not exposed on public network or default port
    reverse-proxy:
        # The official v2 Traefik docker image
        image: traefik:v2.8
        # Enables the web UI and tells Traefik to listen to docker
        command: 
            - --api.insecure=true # when not in prod
            - --providers.docker=true
        #deploy: #this stuff is only used with 'docker stack deploy', ignored by docker compose
            #labels: 
        ports:
        # The HTTP port
        - "80:80"
        # The Web UI (enabled by --api.insecure=true)
        - "8080:8080"
        volumes:
        # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock
    whoami:
        # A container that exposes an API to show its IP address
        image: traefik/whoami
        labels:
        - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"

volumes:
    couchdata:

networks:
  backend:
    driver: bridge

secrets: # available in containers in /run/secrets/secret_name. Long notation can set file perms.
    couch_admin:
        file: ./secrets/couch_admin.txt
    couch_password:
        file: ./secrets/couch_password.txt
    mail_from_address:
        file: ./secrets/mail_from_address_test.txt
    mail_api_key:
        file: ./secrets/mail_api_key_test.txt
    #mail_from_address_test:
        #file: ./secrets/mail_from_address_test.txt
    #mail_api_key_test:
        #file: ./secrets/mail_api_key_test.txt
